In [1]:
import numpy as np
import pandas as pd

How likely is it that you roll doubles when rolling two dice?

In [2]:
n_trials = 100_000 # rows
n_dice = 2 # columns

rolls_array = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice)\
        .reshape(n_trials, n_dice)

rolls_array

array([[4, 1],
       [4, 6],
       [2, 1],
       ...,
       [4, 5],
       [2, 2],
       [1, 4]])

In [3]:
(rolls_array[:,0] == rolls_array[:,1]).mean()

0.16605

In [4]:
# pandas solution

rolls_df = pd.DataFrame(rolls_array)
rolls_df['die1'] = np.random.choice([1, 2, 3, 4, 5, 6], size = 100_000)
rolls_df['die2'] = np.random.choice([1, 2, 3, 4, 5, 6], size = 100_000)
rolls_df

0  1  die1  die2
0      4  1     5     5
1      4  6     5     6
2      2  1     6     4
3      4  1     1     3
4      1  2     3     5
...   .. ..   ...   ...
99995  4  6     1     6
99996  5  1     6     5
99997  4  5     1     6
99998  2  2     5     2
99999  1  4     5     1

[100000 rows x 4 columns]

In [5]:
rolls_df['is_pair'] = (rolls_df.die1 == rolls_df.die2)
rolls_df.is_pair.mean()

0.16498

In [6]:
# numpy solution

a = np.random.choice([1, 2, 3, 4, 5, 6], size = 100_000)
b = np.random.choice([1, 2, 3, 4, 5, 6], size = 100_000)
(a == b).mean()

0.16554

If you flip 8 coins, what is the probability of getting exactly 3 heads? 

What is the probability of getting more than 3 heads?

In [7]:
n_trials = nrows = 100_000
n_coins = ncols = 8

# 1 is heads, 0 is tails (encoded)
coin_flips = np.random.choice([1, 0], n_trials * n_coins)\
.reshape(nrows, ncols)
coin_flips

array([[1, 1, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]])

In [8]:
#axis 1 is sum by row
num_of_heads = coin_flips.sum(axis = 1)
num_of_heads

array([6, 5, 2, ..., 5, 4, 2])

In [9]:
(num_of_heads == 3).mean()

0.21872

In [10]:
(num_of_heads > 3).mean()

0.63769

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
Assuming that Codeup randomly selects an alumni to put on a billboard...

what are the odds that the two billboards I drive past both have data science students on them?

In [12]:
n_trials = 100_000
billboards = 2
# web_dev = 3 (75%)
# data_sci = 1 (25%)

cohort_odds = np.random.choice(['webdev', 'datasci'], 
              size=(n_trials, billboards), 
              p=[.75, .25])
cohort_odds

array([['webdev', 'webdev'],
       ['webdev', 'datasci'],
       ['webdev', 'webdev'],
       ...,
       ['webdev', 'datasci'],
       ['webdev', 'webdev'],
       ['webdev', 'webdev']], dtype='<U7')

In [13]:
cohort_df = pd.DataFrame(cohort_odds)
cohort_df.columns = ['first_billboard', 'second_billboard']
cohort_df

first_billboard second_billboard
0              webdev           webdev
1              webdev          datasci
2              webdev           webdev
3             datasci           webdev
4             datasci          datasci
...               ...              ...
99995         datasci           webdev
99996          webdev          datasci
99997          webdev          datasci
99998          webdev           webdev
99999          webdev           webdev

[100000 rows x 2 columns]

In [14]:
cohort_df['both_ds'] = \
(cohort_df.first_billboard == 'datasci') & (cohort_df.second_billboard == 'datasci')
cohort_df

first_billboard second_billboard  both_ds
0              webdev           webdev    False
1              webdev          datasci    False
2              webdev           webdev    False
3             datasci           webdev    False
4             datasci          datasci     True
...               ...              ...      ...
99995         datasci           webdev    False
99996          webdev          datasci    False
99997          webdev          datasci    False
99998          webdev           webdev    False
99999          webdev           webdev    False

[100000 rows x 3 columns]

In [15]:
cohort_df['both_ds'].mean()

0.06247

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. 

If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 

(Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [16]:
mean = 3 # packages
st_dev = 1.5 # packages
n_days = 5 # days
restocked = 17 # packages
mean_week = mean * n_days

In [17]:
n_weeks = 10000
n_packages_per_day = np.round(np.random.normal(mean, st_dev, size=(n_weeks, n_days)))

In [18]:
n_left_per_week = restocked - np.sum(n_packages_per_day[:, :4], axis=1)

In [19]:
n_left_mask = n_left_per_week > 0
prob_left = np.sum(n_left_mask) / n_weeks
prob_left

0.9308

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.

Women have a mean of 170, sd = 6cm.

Since you have means and standard deviations, you can use np.random.normal to generate observations.

If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [20]:
men_mean = 178
men_std_dev = 8
women_mean = 170
women_std_dev = 6
n_choices = 10000

n_men = np.round(np.random.normal(men_mean, men_std_dev, size=(n_choices)))
n_women = np.round(np.random.normal(women_mean, women_std_dev, size=(n_choices)))

(n_women > n_men).mean()

0.1945

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [21]:
fail = 1 / 250
success = 249/250
chance = [success, fail]

n_students = 50
n_trials = 10000
n_students_100 = 100
n_students_150 = 150
n_students_450 = 450

In [22]:
download = np.random.choice([1,0], n_students * n_trials, p=chance)\
           .reshape(n_trials, n_students)
download

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [23]:
(download.sum(axis = 1) == 50).mean()

0.8196

In [24]:
download_100 = np.random.choice([1,0], n_students_100 * n_trials, p=chance)\
.reshape(n_trials, n_students_100)
download_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [25]:
(download_100.sum(axis=1) == 100).mean()

0.6697

What is the probability that we observe an installation issue within the first 150 students that download anaconda?


How likely is it that 450 students all download anaconda without an issue?

In [26]:
download_450 = np.random.choice([1,0], n_students_450 * n_trials, p=chance)\
.reshape(n_trials, n_students_450)
download_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [27]:
(download_450.sum(axis=1) == 450).mean()

0.1653

In [28]:
download_150 = np.random.choice([1,0], n_students_150 * n_trials, p=chance)\
.reshape(n_trials, n_students_150)
download_150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1]])

In [29]:
(1 - (download_150.sum(axis = 1) == 150).mean()).round(3)

0.451

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 

However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [30]:
n_trials = 10000
shows = .70
no_shows = .30
truck_chance = [shows, no_shows]
n_days = 7

truck_arrives = np.random.choice(['truck', 'none'], n_trials * n_days, p=truck_chance)\
.reshape(n_trials, n_days)
truck_arrives

array([['none', 'truck', 'truck', ..., 'truck', 'truck', 'truck'],
       ['truck', 'truck', 'truck', ..., 'none', 'truck', 'truck'],
       ['truck', 'truck', 'truck', ..., 'truck', 'truck', 'none'],
       ...,
       ['truck', 'none', 'truck', ..., 'none', 'truck', 'none'],
       ['truck', 'truck', 'truck', ..., 'none', 'truck', 'none'],
       ['none', 'truck', 'truck', ..., 'none', 'truck', 'none']],
      dtype='<U5')

In [31]:
((truck_arrives[:,0] == 'none') & (truck_arrives[:,1] == 'none')\
& (truck_arrives[:,2] == 'none')).mean() * 100

2.8000000000000003

In [32]:
trucks = np.random.choice([1,0], size=(100_000, 3), p=truck_chance)
df = pd.DataFrame(trucks)
df.columns = ['day_1', 'day_2', 'day_3']
df.head()

day_1  day_2  day_3
0      1      0      0
1      1      1      1
2      0      1      0
3      1      1      1
4      1      1      0

In [33]:
df['appear'] = df.day_1 + df.day_2 + df.day_3
df.head()

day_1  day_2  day_3  appear
0      1      0      0       1
1      1      1      1       3
2      0      1      0       1
3      1      1      1       3
4      1      1      0       2

In [34]:
(df['appear'] == 0).mean() * 100

2.721

In [35]:
# # How likely is it that a food truck will show up sometime this week?
# trucks = np.random.choice([1,0], size=(100_000, 7), p=[.7,.3])
# df = pd.DataFrame(trucks)

# df['appear'] = df.sum(axis=1)
# (df.appear > 0).mean()

How likely is it that a food truck will show up sometime this week?

In [36]:
trucks = np.random.choice([1, 0], size=(100_000, 7), p=truck_chance)
df = pd.DataFrame(trucks)
df.head()

0  1  2  3  4  5  6
0  1  1  1  1  1  0  1
1  1  1  0  1  1  1  1
2  1  0  1  1  1  0  1
3  1  0  1  1  0  1  1
4  1  1  1  0  1  0  1

In [37]:
df['appear'] = df.sum(axis = 1)
df.head()

0  1  2  3  4  5  6  appear
0  1  1  1  1  1  0  1       6
1  1  1  0  1  1  1  1       6
2  1  0  1  1  1  0  1       5
3  1  0  1  1  0  1  1       5
4  1  1  1  0  1  0  1       5

In [38]:
(df['appear'] > 0).mean()

0.99983

If 23 people are in the same room, what are the odds that two of them share a birthday? 

What if it's 20 people? 40?

In [39]:
n_trials = 100000 # rows
n_people = 23 # columns

birthday = np.random.choice(range(1,366), size=(n_trials, n_people))
df_birthday = pd.DataFrame(birthday)
df_birthday.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   29   31  144  234  336  200  241  201  100   96  ...  240  122  296   17   
1  346  168   28  226  120  277  248  142  356  124  ...   54  215   26  303   
2  157  158   46  230  127  205  236  233   51   88  ...  353  338   83  354   
3   44  290  343  123   24  325  260  203   21  238  ...  232  229  349   98   
4  254  123  329   66  352   23   30   30  253   75  ...  153   72  359  242   

    17   18   19   20   21   22  
0  197  140  157  130  216   46  
1   47  279  130  193  211  147  
2  102  189  132   44    4  284  
3  213  129   88  135  183  287  
4   82   36   18  190  292   15  

[5 rows x 23 columns]

In [40]:
df_birthday['unique'] = df.nunique(axis=1)
df_birthday.head()

0    1    2    3    4    5    6    7    8    9  ...   14   15   16   17  \
0   29   31  144  234  336  200  241  201  100   96  ...  122  296   17  197   
1  346  168   28  226  120  277  248  142  356  124  ...  215   26  303   47   
2  157  158   46  230  127  205  236  233   51   88  ...  338   83  354  102   
3   44  290  343  123   24  325  260  203   21  238  ...  229  349   98  213   
4  254  123  329   66  352   23   30   30  253   75  ...   72  359  242   82   

    18   19   20   21   22  unique  
0  140  157  130  216   46       3  
1  279  130  193  211  147       3  
2  189  132   44    4  284       3  
3  129   88  135  183  287       3  
4   36   18  190  292   15       3  

[5 rows x 24 columns]

In [43]:
(df.nunique(axis = 1) != 23).mean()

1.0

In [ ]:
df_birthday = df_birthday.drop(columns=["n_unique"])


In [ ]:
df_birthday